import Head from "next/head";
import styles from "../styles/Home.module.css";

function NextPage() {
  return (
    <div className="App">
      <Head>
        <title>Next Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className="App-header">
          <h1>Next Page</h1>
          <hr className="fullWidth" />
          <p>Hello there</p>
        </header>
      </main>
    </div>
  );
}

export default NextPage;
